### ISSUE TITLE
タスク_画面下部に共通の画面遷移ボタンを追加する

### ISSUE THREAD

**Issue by NekoSarada1101** [NekoSarada1101/SNap-develop#78]
## タスクリスト 
- [ ] 画面をDataBindingに変換する
- [ ] 画面下部にボタンを追加する
- [ ] プルリクエストを画面ごとに作る（closed # にissue番号を書かないように）

**Comment by rokkou** [comment]
プルリクエストを画面ごとに作るの忘れてました。
すいません。
